apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: darshankp1/backend-app:v1
        ports:
        - containerPort: 5000
        sudo apt update 
sudo apt install apt-transport-https ca-certificates curl software-properties-common -y 
sudo apt install docker.io -y
sudo apt update
sudo apt install openjdk-21-jdk -y
sudo rm jenkins.war
sudo rm -rf ~/.jenkins
wget https://get.jenkins.io/war-stable/latest/jenkins.war
ls
java -jar jenkins.war --httpPort=8090
