pipeline {
    agent any

    environment {
        IMAGE_NAME = "darshankp1/backend-app"
        TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Build Backend Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG backend/'
            }
        }

        stage('Docker Login & Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                sh '''
                export KUBECONFIG=/home/darshan_kp/.kube/config
                kubectl apply -f deployment.yaml
                kubectl set image deployment/backend-deployment \
                backend-container=$IMAGE_NAME:$TAG --record
                '''
            }
        }
    }
}